name: CI
on:
  push:
    branches: [main]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run build
      - run: npm run build:static
      - run: npm test
      - run: npm run type-check
      - run: npm run lint
      - name: install playwright system dependencies
        working-directory: ./packages/e2e
        if: runner.os == 'Linux'
        run: sudo npx playwright install-deps chromium firefox webkit
      - name: install playwright dependencies
        working-directory: ./packages/e2e
        run: npx playwright install chromium firefox
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: install playwright webkit dependency
        working-directory: ./packages/e2e
        run: npx playwright install webkit
        if: runner.os == 'Linux'
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: e2e
        working-directory: ./packages/e2e
        run: npm run e2e:headless
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: e2e firefox
        working-directory: ./packages/e2e
        run: npm run e2e:firefox:headless -- --timeout=2100000
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: e2e webkit
        working-directory: ./packages/e2e
        run: npm run e2e:webkit:headless -- --timeout=2100000
        if: runner.os == 'Linux'
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
